# A  propos des autheurs {#author .unnumbered}

Ce livre est pemièrement met ensemble par moi-même (Yihui Xie), pour mettre en oeuvre l'existence de documentation en R pour le package **rmarkdown** et le siteweb de  **rmarkdown**, que J.J. Allaire and Garrett Grolemund ont contribués principalement.

## Yihui Xie {-}

Yihui Xie (<https://yihui.name>) est un ingénieur en génie logiciel chez RStudio (<https://www.rstudio.com>). Il a obténu son Doctorat dans le département de statistique de l'Université publique de  Iowa. Il s'intéresse à la graphique interactive statistique et à la statistique pour la machine. En tant que utilisateur de R, il a déjà écris beaucoups de package en R, comme **knitr**, **bookdown**, **blogdown**, **xaringan**, **tinytex**, **animation**, **DT**, **tufte**, **formatR**, **fun**, **xfun**, **mime**, **highr**, **servr**, and **Rd2roxygen**, parmis lequel le package **animation** a gagné le prix de John M. Chambers Statistical Software Award (ASA) en 2009. Il est aussi co-autheur de quelques packages R comme **shiny**, **rmarkdown**, et **leaflet**.

Il est l'autheur de deux livres, _Dynamic Documents with knitr_ [@xie2015], et  _bookdown: Authoring Books and Technical Documents with R Markdown_ [@xie2016], et co autheur de deux livres, _blogdown: Creating Websites with R Markdown_ [@xie2017], and _R Markdown: The Definitive Guide_ [@xie2018].

En 2006, il a fondé the Capital of Statistics(le capital de la statistique) (<https://cosx.org>), dans laquelle grandi dans une grande communauté en ligne dans le monde de statistique en Chine. Il a initialisé la conférence en R en Chine en 2008,  et a déjà organisé des conférences concernant R en Chine depuis ce temps là. Durant son étude en Doctorat à l'Université  publique de  Iowa, il a gagné le prix de Vince Sposito Statistical Computing Award (2011) et le prix de  Snedecor Award (2012) dans le Départément de Statistique.

Il est rarement dans le réseau social Twitter (https://twitter.com/xieyihui), et la plupart de temps vous pouvez le voir chez GitHub (https://github.com/yihui).

Il adore les aliments épicés et la literature classique Chinoise.

## J.J. Allaire {-}

J.J. Allaire est le fondateur de Rstudio et le créateur de RStudio IDE. J.J. Allaire est un autheur de plusieurs packages dans l'écosystème de R Markdown dont inclus **rmarkdown**, **flexdashboard**, **learnr**, et **radix**. 

## Garrett Grolemund {-}

Garrett Grolemund est le co-autheur de _R for Data Science_ and author of _Hands-On Programming with R_. Il a écris aussi le package en R **lubridate** et travail pour le RStudio pour but d'entrainer les ingénieurs en science de donnée avec R et de Tidyverse. Si tu utilise R pour toi-même, vous pouvez quand même reconnaître Garrett dans son vidéo de tutorial dans le site web de Datacamp.com  et de l'O'Reilly media, ou bien de séries populaire R cheatsheets distribué par RStudio.

Garrett a obténu son diplôme de doctorat en Statistique de l'Université de Rice en 2012 sous le guide de Hadley Wickham. Avant cela, il a obténu son Maitrise en Psychologie provenant de l'Université de Harvard et rarement assisté le cour de droit. Garrett a été presque l'un des promoteurs de la documentation et de l'explication de chaque détail de packages Shiny, R Markdown, et le Tidyverse.